### ISSUE TITLE
GUI not drawing (black window)

### ISSUE THREAD

**Issue by unfa** [DISTRHO/ProM#1]
I'm running KX Studio

This is how ProM looks like hosted in Carla:

![prom](https://cloud.githubusercontent.com/assets/491704/9018365/afd3c56e-37de-11e5-8596-e5189c4e4d74.png)

Probably related to https://github.com/x42/meters.lv2/issues/7

**Comment by unfa** [comment]
Related? https://github.com/DISTRHO/MVerb/issues/1

**Comment by falkTX** [comment]
ProM UI is purely openGL, so it's this will be an issue with your graphics drivers.

**Comment by unfa** [comment]
I'm using Bumblebee, so I'll try running Carla host with optirun and see if it changes anything.

**Comment by unfa** [comment]
Yep, this seem s to be the issue. When I run

```
     optirun carla
```

The plugin works.

When I run Carla regularly

```
    carla
```

It doesnt (black window).

I also tested Mverb and the results are a bit different, there's a problem with the LV2 version.

optirun carla: The internal version of the plugin works fine, the external LV2 doesn't ever open it's GUI window though.

carla: Both internal and external LV2 versions display a black or messed up windows.

**Comment by falkTX** [comment]
I have to close this issue. from what I understood it's all about your graphics drivers and setup.
MVerb and meters.lv2 have the same issue, so really not something specific to this project.
