### ISSUE TITLE
ffmpeg showcqt version?

### ISSUE THREAD

**Issue by mxmilkiib** [DISTRHO/ProM#2]
[Here is an example](https://www.youtube.com/watch?v=bVU_mnHizgo), rendered using the [showcqt-bash](https://github.com/mfcc64/showcqt-bash) wrapper script with the settings from [visualizer.lua](https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua) for mpv.

**Comment by falkTX** [comment]
that does not seem to be projectm related, so it would be a totally different product.

**Comment by mxmilkiib** [comment]
Yes, but I thought I might as well make the suggestion on the closest existing project

**Comment by falkTX** [comment]
Sure, but it is not related to this project.
Better to ask somewhere else, someone else, to try and take such a project.
