### ISSUE TITLE
libprojectM.so.2 vs libprojectM.so.3

### ISSUE THREAD

**Issue by mxmilkiib** [DISTRHO/ProM#3]
https://i.imgur.com/oDt6lk6.png using the community projectm package on Arch

**Comment by falkTX** [comment]
just rebuild the plugin then

**Comment by mxmilkb** [comment]
I was using both projectm-git and dpf-plugins-git. Downgrading both to the binary packages resolved the problem.

**Comment by mxmilkiib** [comment]
I thought I had rebuilt both packages, but apparently I hadn't, this resolved the issue, thanks!
