### ISSUE TITLE
`libprojectM/projectM-opengl.h: No such file or directory`

### ISSUE THREAD

**Issue by dromer** [DISTRHO/ProM#4]
On debian 11

With `HAVE_PROJECTM` true or false compilation fails with:

```
DistrhoUIProM.cpp:17:10: fatal error: libprojectM/projectM-opengl.h: No such file or directory
   17 | #include "libprojectM/projectM-opengl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by falkTX** [comment]
@dromer should be fixed now, please confirm

**Comment by dromer** [comment]
Yes!

Standalone fails, but LV2, VST2 and VST3 (partially) work.

Only issue is with window resizing and fullscreen:
 - LV2: resizing glitches, fullscreen works
 - VST2: resizing works, fullscreen does not (sticks to one corner)
 - VST3: resizing works, fullscreen does not (sticks to one corner, with resize still available)

**Comment by falkTX** [comment]
fullscreen should not even be possible. and in any case it would be a different issue.
standalone is removed from the build, if you have something in bin/ it would be an old binary.
thanks for confirming the fix

**Comment by dromer** [comment]
Yeah FS is a window-manager thing I suppose -> `alt+f11` in fluxbox
There is some other difference in window properties between the 3 plugins:
- LV2: minimize, maximize, close
- VST2: minimize, close
- VST3: close

**Comment by falkTX** [comment]
LV2 supports host-side resizing, so that is expected vs VST2.
The VST3 being based on juce and not custom implementation explains why it would be different. I like that it hides the minimize button, I need to see how to do that for the others.
VST3 does support host-side resizing like LV2, but I havent implemented that (in either Carla or DPF)
