### ISSUE TITLE
VST Windows 10 + Reaper gets black screen

### ISSUE THREAD

**Issue by KonradFoit** [DISTRHO/ProM#6]
Hello,
I tried to run this as VST and VST3, both x64 and x86 on Windows 10 under Reaper and no matter what I do, I always get black screen. Reaper keeps going fine.
My starting point is to just unpack x64 build artifact and move "ProM.vst3" directory into my plugins location. 
One thing raised my suspicion, however I might be totally wrong/
In file `plugins/ProM/projectM/src/libprojectM/projectM.cpp` line 192:
```
#ifdef WIN32
    _settings.presetURL = config.read<string> ( "Preset Path", "/usr/local/share/projectM/presets" );
#endif
```
That would suggest that it has to be run at least under cygwin, however that is not possible when Reaper is a host. 

BR,
Konrad

**Comment by falkTX** [comment]
Those settings are not used, assuming plugin is installed by copying the vst2/vst3 bundles as-is.
The black window issue should be fixed now with the latest builds, I will test it on a real windows PC before release.

**Comment by falkTX** [comment]
Latest build works fine here. 🚀 

![image](https://user-images.githubusercontent.com/1334853/199095618-9868edf5-a0e3-436d-b258-80df6541bb6b.png)
